### PR TITLE
Stock view

### PR DESCRIPTION
**Pull request by jaakop**
Added stock view

### CODE REVIEW

**Comment by jaakop** [comment]
Now routing works Pog

**Comment by jaakop** [comment]
image

**Comment by jaakop** [comment]
Now hovering over the chart works

**Comment by jaakop** [comment]
Can view current changes at [https://ambitious-cliff-0e6951003-5.westeurope.azurestaticapps.net/](https://ambitious-cliff-0e6951003-5.westeurope.azurestaticapps.net/)

**Review by JHanhivaara — APPROVED** [review]

**Pull request merged**
